DEDUPLICATION_ID_NAME = 'deduplication_id'
ROW_ID = 'row_number'
ROW_ID_CENTRAL = 'row_number_central'
N_QUERIES = 999
CONVERGENCE_THRESHOLD = 0.01

N_PERFECT_MATCHES_TRAIN = 3
MIN_NR_ENTRIES = 10
UNCERTAINTY_IMPROVEMENT_THRESHOLD = 0.01
UNCERTAINTY_THRESHOLD = 0.1
